# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'coffeescript', :input => 'static/coffee', :output => 'static/js/'

guard 'sass', :input => 'static/sass', :output => 'static/css'

guard 'livereload' do
  watch(%r{templates/.+\.(html)})
  watch(%r{static/.+\.(coffee|scss)})
end
